// test_nxdn_dsdcc.cpp
//
// Verifies the DSDcc backend's NXDN metadata path: fed a known-good
// NXDN48 sample (generated by tools/nxdn_make_sample at build time),
// DsdccDecoder in "nxdn48" mode must emit call events carrying the
// encoded RAN / source / talkgroup as structured fields -- the same
// field shape the dsd-fme backend produces. The sample encodes
// RAN=9, source=100, group talkgroup=200.
//
// (DSDcc's NXDN decode is fragile on real off-air signals; this pins the
// wrapper's field mapping on a clean signal it can decode.)

#include "../src/dsdcc_decoder.hpp"
#include <cstdio>
#include <cstdint>
#include <set>
#include <string>
#include <vector>

using namespace dsdsrv;

int main(int argc, char** argv) {
    if (argc < 2) {
        std::printf("SKIPPED: usage: test_nxdn_dsdcc <nxdn48 .dis sample>\n");
        return 0;
    }
    FILE* f = std::fopen(argv[1], "rb");
    if (!f) { std::printf("SKIPPED: cannot open sample %s\n", argv[1]); return 0; }
    std::vector<int16_t> pcm; int16_t s;
    while (std::fread(&s, sizeof(s), 1, f) == 1) pcm.push_back(s);
    std::fclose(f);

    std::set<std::string> rans, sources, talkgroups, kinds;
    DsdccDecoder dec;
    DsdccConfig cfg;
    cfg.mode = "nxdn48";
    cfg.input_sample_rate_hz = 48000;
    bool ok = dec.start(cfg,
        [&](const DsdEvent& e) {
            kinds.insert(e.kind);
            if (!e.ran.empty()) rans.insert(e.ran);
            if (!e.source_id.empty()) sources.insert(e.source_id);
            if (!e.talkgroup.empty()) talkgroups.insert(e.talkgroup);
        }, nullptr);

    int failures = 0;
    auto check = [&](bool c, const std::string& what) {
        std::printf("  %s: %s\n", c ? "OK" : "FAIL", what.c_str());
        if (!c) ++failures;
    };

    check(ok, "decoder starts in nxdn48 mode");
    for (std::size_t i = 0; i < pcm.size(); i += 1024) {
        std::size_t n = std::min<std::size_t>(1024, pcm.size() - i);
        dec.write_audio(pcm.data() + i, n);
    }
    dec.stop();

    check(sources.count("100") == 1, "NXDN event carries the encoded source (100)");
    check(talkgroups.count("200") == 1, "NXDN event carries the encoded group talkgroup (200)");
    check(rans.count("9") == 1, "NXDN event carries the encoded RAN (9)");
    check(kinds.count("call") == 1, "NXDN metadata surfaces as call events");

    if (failures == 0) { std::printf("\nALL NXDN DSDCC TESTS PASSED\n"); return 0; }
    std::printf("\n%d CHECK(S) FAILED\n", failures);
    return 1;
}
